//@version=5
strategy("20 MA Reversion Strategy", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=10)

percentFromMA = 0.0020 // 0.18% MOVE previous use / now testing with .15%
ma20 = ta.sma(close, 20)

longPriceDive = close < ma20 * (1 - percentFromMA)
shortPriceDive = close > ma20 * (1 + percentFromMA)
// entry condition
longCondition = longPriceDive and strategy.position_size == 0
shortCondition = shortPriceDive and strategy.position_size == 0
// keep track of high and low
var float highSinceDive = na
var float lowSinceDive = na

// entry conditions
if (longCondition)
    highSinceDive := high
else if (strategy.position_size > 0)
    highSinceDive := math.max(highSinceDive, high)

if (shortCondition)
    lowSinceDive := low
else if (strategy.position_size < 0)
    lowSinceDive := math.min(lowSinceDive, low)
//entrance
if (longCondition)
    strategy.entry("Long", strategy.long)
if (shortCondition)
    strategy.entry("Short", strategy.short)

//exit
exitLongCondition = strategy.position_size > 0 and high > highSinceDive
exitShortCondition = strategy.position_size < 0 and low < lowSinceDive
if (exitLongCondition)
    strategy.close("Long")
if (exitShortCondition)
    strategy.close("Short")
//tp
takeProfitLong = strategy.position_size > 0 and close >= ma20
takeProfitShort = strategy.position_size < 0 and close <= ma20

if (takeProfitLong)
    strategy.close("Long")
if (takeProfitShort)
    strategy.close("Short")

//plot line
plot(ma20, color=color.blue)